/-
Copyright (c) 2026 Logos Library Formalization Project. All rights reserved.
Released under MIT license as described in the file LICENSE.
Author: Adam Bornemann
Filename: Riemann/ZetaData.lean
-/
import Mathlib.Data.Complex.Basic
import Mathlib.Data.Nat.Prime.Basic
import Mathlib.Tactic
/-!
=====================================================================
# THE RIEMANN ZETA DATA
=====================================================================
Via the Curry-Howard method...
because the real thing would melt every computer ever built.

## Overview

This file axiomatizes the classical objects of the Riemann zeta
function as typed data with built-in consistency conditions.  No
construction of ζ from scratch — only the structural invariants
that the later files (ExplicitFormula, LocalFactor, GearAssembly,
Positivity) need as their interface.

This is the number-theoretic analogue of `CliffordPeriodicity/Basic.lean`.
Where that file defined the three division algebras and the Clifford
classification data, this file defines the critical strip, the
functional equation involution, and the zero classification data.

## The Key Objects

  1. **The Critical Strip**:  {s ∈ ℂ | 0 < Re(s) < 1}
  2. **The Critical Line**:  {s ∈ ℂ | Re(s) = 1/2}
  3. **The Zeta Reflection**:  s ↦ 1 − s
  4. **ZeroData**:  individual non-trivial zero with consistency
  5. **CompletedZetaData**:  the master axiomatization of ξ(s)
  6. **CriticalLineConfinement**:  RH as a type

## The Gear Interface

The functional equation ξ(s) = ξ(1−s) is a ℤ/2 involution on the
critical strip with fixed-point locus Re(s) = 1/2.  This is
**Axiom I** (Involution) of the Möbius tooth profile, applied to
the zeta data.

The `InvolutionData` structure at the end of this file packages
this as a reusable interface that `LocalFactor.lean` will
instantiate at each place of ℚ.

## The Symmetry Group

The non-trivial zeros of ζ carry a Klein four-group V₄ ≅ ℤ/2 × ℤ/2
of symmetries, generated by:

    σ : s ↦ 1 − s     (functional equation)
    τ : s ↦ s̄          (complex conjugation)

Their composition σ ∘ τ = τ ∘ σ : s ↦ 1 − s̄ is the **Schwarz
reflection** of the critical strip.  Its fixed-point set is
precisely the critical line Re(s) = 1/2.

**RH is the statement that σ and τ agree on every zero:**
    ∀ ρ, ξ(ρ) = 0 → 1 − ρ = ρ̄

When this holds, the four-element orbit {ρ, 1−ρ, ρ̄, 1−ρ̄}
collapses to the two-element set {ρ, ρ̄} on the critical line.

=====================================================================
-/

namespace Riemann

open Complex

/-!
=====================================================================
## The Geometry of the Critical Strip
=====================================================================

The critical strip 0 < Re(s) < 1 is the arena where the non-trivial
zeros live.  The critical line Re(s) = 1/2 is the conjectured
home of ALL of them.

The right half-plane Re(s) > 1 is where the Euler product
converges absolutely — the "classical" domain of ζ(s).

    ℂ
    │
    │  Re(s) > 1:  Euler product converges
    │  ─────────────────────────────────────
    │  0 < Re(s) < 1:  CRITICAL STRIP
    │       Re(s) = 1/2:  critical line
    │  ─────────────────────────────────────
    │  Re(s) < 0:  trivial zeros at −2, −4, ...
    │
=====================================================================
-/

section CriticalStripGeometry

/-- **The critical strip**: the open vertical strip 0 < Re(s) < 1.

    All non-trivial zeros of the Riemann zeta function lie here.
    The functional equation maps the strip to itself. -/
def CriticalStrip : Set ℂ := {s : ℂ | 0 < s.re ∧ s.re < 1}

/-- **The critical line**: the vertical line Re(s) = 1/2.

    RH asserts that ALL non-trivial zeros lie on this line.
    It is the fixed-point locus of the Schwarz reflection
    s ↦ 1 − s̄ (the composition of the two generators of V₄). -/
def CriticalLine : Set ℂ := {s : ℂ | s.re = 1 / 2}

/-- **The right half-plane**: Re(s) > 1.

    The domain of absolute convergence of the Dirichlet series
    ζ(s) = Σ n⁻ˢ and the Euler product Π_p (1 − p⁻ˢ)⁻¹.
    No zeros here — the Euler product is nonvanishing. -/
def RightHalfPlane : Set ℂ := {s : ℂ | 1 < s.re}

/-- The critical line lies inside the critical strip.

    1/2 ∈ (0, 1).  The line is the midline of the strip. -/
theorem criticalLine_subset_strip : CriticalLine ⊆ CriticalStrip := by
  intro s hs
  simp only [CriticalLine, Set.mem_setOf_eq] at hs
  simp only [CriticalStrip, Set.mem_setOf_eq]
  rw [hs]; constructor <;> norm_num

/-- The right half-plane is disjoint from the critical strip.

    No zero can be both "in the strip" and "in the convergence
    region" — the Euler product kills zeros to the right of Re(s) = 1. -/
theorem rightHalfPlane_disjoint_strip :
    Disjoint RightHalfPlane CriticalStrip :=
  Set.disjoint_left.mpr fun _ hs hc => by
    simp only [RightHalfPlane, CriticalStrip, Set.mem_setOf_eq] at *
    linarith

end CriticalStripGeometry


/-!
=====================================================================
## The Zeta Reflection: Axiom I
=====================================================================

The map s ↦ 1 − s is the functional equation involution.
It is the FIRST axiom of the tooth profile:

    **Axiom I (Involution)**: There exists a map σ : ℂ → ℂ
    with σ² = id, preserving the critical strip, whose
    real-part fixed locus is the critical line.

For the Riemann zeta function, σ = zetaReflection.
For a local factor at place v, σ will be the SAME map —
the functional equation is a GLOBAL symmetry that each
local factor must respect individually.

=====================================================================
-/

section ZetaReflection

/-- **The zeta reflection**: s ↦ 1 − s.

    The generator of the functional equation symmetry.
    Maps the critical strip to itself, swapping the left
    half (0 < Re(s) < 1/2) with the right half (1/2 < Re(s) < 1).
    Fixes the critical line Re(s) = 1/2 setwise.

    This is the number-theoretic analogue of:
    - clockConjugate on the Bott clock (discrete)
    - J (modular conjugation) in Tomita theory (operator)

    It satisfies Axiom I of the tooth profile: involution. -/
def zetaReflection (s : ℂ) : ℂ := 1 - s

-- ═══════════════════════════════════════════════════════════════
-- Component lemmas
-- ═══════════════════════════════════════════════════════════════

@[simp] theorem zetaReflection_re (s : ℂ) :
    (zetaReflection s).re = 1 - s.re := by
  unfold zetaReflection; simp

@[simp] theorem zetaReflection_im (s : ℂ) :
    (zetaReflection s).im = -s.im := by
  unfold zetaReflection; simp

-- ═══════════════════════════════════════════════════════════════
-- The four axiom-relevant properties
-- ═══════════════════════════════════════════════════════════════

/-- **INVOLUTION**: Two reflections return to start.

    ζRefl(ζRefl(s)) = 1 − (1 − s) = s.

    This is π₁(strip) = ℤ₂: the critical strip with its
    two boundaries identified by the functional equation
    is a topological cylinder (or Möbius strip, depending
    on the sign). The reflection generates the deck
    transformation of the double cover. -/
theorem zetaReflection_involution (s : ℂ) :
    zetaReflection (zetaReflection s) = s := by
  simp [zetaReflection]

/-- **STRIP PRESERVATION**: The reflection maps the critical
    strip to itself.

    If 0 < Re(s) < 1, then 0 < 1 − Re(s) < 1.
    The strip is the MAXIMAL open set preserved by the reflection
    (among vertical strips). -/
theorem zetaReflection_mem_strip {s : ℂ} (hs : s ∈ CriticalStrip) :
    zetaReflection s ∈ CriticalStrip := by
  simp only [CriticalStrip, Set.mem_setOf_eq, zetaReflection_re] at *
  constructor <;> linarith

/-- **LINE PRESERVATION**: The reflection maps the critical
    line to itself.

    If Re(s) = 1/2, then Re(1−s) = 1 − 1/2 = 1/2.
    The critical line is a FIXED SET of the reflection (setwise). -/
theorem zetaReflection_mem_line {s : ℂ} (hs : s ∈ CriticalLine) :
    zetaReflection s ∈ CriticalLine := by
  simp only [CriticalLine, Set.mem_setOf_eq, zetaReflection_re] at *
  linarith

/-- **FIXED-POINT CHARACTERIZATION**: The real part is fixed
    by the reflection if and only if it equals 1/2.

    Re(1−s) = Re(s)  ↔  1 − Re(s) = Re(s)  ↔  Re(s) = 1/2.

    This identifies the critical line as the fixed-point locus
    of the involution ON THE REAL PART.  It is the ℤ/2-theoretic
    reason the critical line is special: it is the unique vertical
    line preserved POINTWISE (in the Re direction) by s ↦ 1−s.

    Compare with the Bott clock: clockConjugate has fixed points
    {0, 4}, and 9 mod 8 = 1 ≠ 0, 4 means Cl(9) is NOT self-dual
    under conjugation — which is WHY it gets complex structure. -/
theorem zetaReflection_re_fixed_iff (s : ℂ) :
    (zetaReflection s).re = s.re ↔ s.re = 1 / 2 := by
  simp only [zetaReflection_re]
  constructor <;> intro h <;> linarith

end ZetaReflection


/-!
=====================================================================
## The Full Symmetry Group: Klein V₄
=====================================================================

The non-trivial zeros carry a Klein four-group of symmetries:

    id  : s ↦ s           (identity)
    σ   : s ↦ 1 − s       (functional equation)
    τ   : s ↦ s̄            (complex conjugation)
    στ  : s ↦ 1 − s̄        (Schwarz reflection)

The group table:

    ∘  │ id   σ    τ    στ
    ───┼─────────────────────
    id │ id   σ    τ    στ
    σ  │ σ    id   στ   τ
    τ  │ τ    στ   id   σ
    στ │ στ   τ    σ    id

Every element has order 2.  The group is V₄ ≅ ℤ/2 × ℤ/2.

**RH** says: every zero is fixed by στ.  Equivalently,
σ and τ agree on every zero: 1 − ρ = ρ̄.  Equivalently,
the orbit of every zero under V₄ has size ≤ 2 (not 4).

=====================================================================
-/

section KleinFourGroup

/-- **The Schwarz reflection**: s ↦ 1 − s̄.

    The composition of the functional equation reflection and
    complex conjugation.  Its fixed-point set is the full
    critical line {s : Re(s) = 1/2} — unlike zetaReflection,
    whose only fixed POINT is s = 1/2 itself.

    This is because 1 − s̄ = s requires:
      Re: 1 − Re(s) = Re(s), so Re(s) = 1/2
      Im: Im(s) = Im(s), always true

    The Schwarz reflection fixes every point on the critical line,
    regardless of imaginary part.  THIS is the involution whose
    fixed set is the critical line AS A SET, not just a point. -/
def zetaSchwarzReflection (s : ℂ) : ℂ :=
  ⟨1 - s.re, s.im⟩

@[simp] theorem zetaSchwarzReflection_re (s : ℂ) :
    (zetaSchwarzReflection s).re = 1 - s.re := rfl

@[simp] theorem zetaSchwarzReflection_im (s : ℂ) :
    (zetaSchwarzReflection s).im = s.im := rfl

/-- The Schwarz reflection is an involution. -/
theorem zetaSchwarzReflection_involution (s : ℂ) :
    zetaSchwarzReflection (zetaSchwarzReflection s) = s := by
  rw [@Complex.ext_iff]
  simp only [zetaSchwarzReflection_re, sub_sub_cancel, zetaSchwarzReflection_im, and_self]

/-- **THE CRITICAL LINE IS THE SCHWARZ FIXED SET.**

    zetaSchwarzReflection(s) = s  ↔  Re(s) = 1/2.

    This is the COMPLETE fixed-point characterization: not just
    the real part, but the full complex number is fixed.  The
    imaginary part is automatically preserved.

    This is the deepest geometric reason the critical line is
    special: it is the fixed-point set of the UNIQUE anti-holomorphic
    involution of the critical strip that extends the functional equation. -/
theorem zetaSchwarzReflection_fixed_iff (s : ℂ) :
    zetaSchwarzReflection s = s ↔ s.re = 1 / 2 := by
  constructor
  · intro h
    have : (zetaSchwarzReflection s).re = s.re := by rw [h]
    simp at this; linarith
  · intro h
    rw [@Complex.ext_iff]
    simp only [zetaSchwarzReflection_re, zetaSchwarzReflection_im, and_true]
    linarith

/-- The Schwarz reflection preserves the critical strip. -/
theorem zetaSchwarzReflection_mem_strip {s : ℂ}
    (hs : s ∈ CriticalStrip) :
    zetaSchwarzReflection s ∈ CriticalStrip := by
  simp only [CriticalStrip, Set.mem_setOf_eq, zetaSchwarzReflection_re] at *
  constructor <;> linarith

-- ═══════════════════════════════════════════════════════════════
-- The V₄ group structure
-- ═══════════════════════════════════════════════════════════════

/-- The four symmetries of the zero set, as an enumerated type.

    This is the analogue of CliffordBaseField — a discrete
    classification that partitions the symmetry. -/
inductive ZetaSymmetry : Type where
  /-- The identity: s ↦ s -/
  | id : ZetaSymmetry
  /-- Functional equation: s ↦ 1 − s -/
  | reflection : ZetaSymmetry
  /-- Complex conjugation: s ↦ s̄ -/
  | conjugation : ZetaSymmetry
  /-- Schwarz reflection: s ↦ 1 − s̄ -/
  | schwarz : ZetaSymmetry
  deriving DecidableEq, Repr

/-- The action of each symmetry on ℂ. -/
def ZetaSymmetry.act : ZetaSymmetry → ℂ → ℂ
  | .id          => fun s => s
  | .reflection  => zetaReflection
  | .conjugation => fun s => starRingEnd ℂ s
  | .schwarz     => zetaSchwarzReflection

/-- Every element of V₄ is an involution. -/
theorem zetaSymmetry_all_involutions (g : ZetaSymmetry) (s : ℂ) :
    g.act (g.act s) = s := by
  cases g with
  | id => rfl
  | reflection => exact zetaReflection_involution s
  | conjugation =>
    simp only [ZetaSymmetry.act, starRingEnd_apply, star_star]
  | schwarz => exact zetaSchwarzReflection_involution s

end KleinFourGroup


/-!
=====================================================================
## Zero Classification Data
=====================================================================

A non-trivial zero is a point ρ in the critical strip where ξ
vanishes.  The functional equation pairs each zero ρ with 1 − ρ.
Conjugation pairs ρ with ρ̄.  Together, zeros come in orbits of
size 1, 2, or 4 under V₄.

    Orbit size 1:  ρ = 1 − ρ = ρ̄ = 1 − ρ̄  →  ρ = 1/2 (impossible: ξ(1/2) ≠ 0)
    Orbit size 2:  ρ = ρ̄ (real) but ρ ≠ 1 − ρ, OR ρ ≠ ρ̄ but 1 − ρ = ρ̄ (on critical line)
    Orbit size 4:  all four distinct (off the critical line AND not real)

RH says: every orbit has size ≤ 2, and specifically the second
type: ρ and ρ̄ = 1 − ρ, both on the critical line.

=====================================================================
-/

section ZeroData

/-- **A non-trivial zero of the completed zeta function.**

    Packages the position ρ, its location in the critical strip,
    and its multiplicity.  The consistency conditions ensure ρ
    is a genuine zero inside the strip.

    This is the analogue of a single entry in the Clifford
    periodicity table: typed data with built-in invariants. -/
structure ZeroData where
  /-- The zero's position in the complex plane -/
  ρ : ℂ
  /-- The zero lies in the critical strip -/
  hStrip : ρ ∈ CriticalStrip
  /-- The multiplicity of the zero (positive) -/
  multiplicity : ℕ
  /-- Multiplicity is at least 1 -/
  hMult : 0 < multiplicity

/-- A zero is on the critical line if Re(ρ) = 1/2. -/
def ZeroData.onCriticalLine (z : ZeroData) : Prop :=
  z.ρ ∈ CriticalLine

/-- A zero is self-dual under the functional equation if ρ = 1 − ρ̄.
    Equivalently, Re(ρ) = 1/2.  Equivalently, the Schwarz
    reflection fixes ρ. -/
def ZeroData.selfDual (z : ZeroData) : Prop :=
  zetaSchwarzReflection z.ρ = z.ρ

/-- Self-duality is equivalent to being on the critical line. -/
theorem ZeroData.selfDual_iff_onLine (z : ZeroData) :
    z.selfDual ↔ z.onCriticalLine := by
  simp [ZeroData.selfDual, ZeroData.onCriticalLine,
        zetaSchwarzReflection_fixed_iff, CriticalLine]

end ZeroData


/-!
=====================================================================
## The Completed Zeta Axiomatization
=====================================================================

The structure `CompletedZetaData` axiomatizes the completed
(Riemann xi) function ξ(s) = ½s(s−1)π^{−s/2}Γ(s/2)ζ(s).

Unlike ζ(s), the function ξ is:
  - Entire (no poles — the s(s−1) factor cancels the pole at s = 1)
  - Symmetric: ξ(s) = ξ(1−s)  (clean functional equation)
  - Real-valued on the critical line

Its zeros are EXACTLY the non-trivial zeros of ζ(s).

We axiomatize ξ rather than ζ because:
  1. The functional equation is cleaner (no gamma factors)
  2. The zero set is the same
  3. The involution structure is manifest

The Euler product for ζ(s) — the arithmetic content — will be
introduced in `LocalFactor.lean` through the relationship
ξ(s) = ½s(s−1)π^{−s/2}Γ(s/2) · Π_p (1 − p⁻ˢ)⁻¹.

=====================================================================
-/

section CompletedZeta

/-- **The completed zeta function, axiomatized.**

    This is the analogue of `CliffordData`: a structure packaging
    a function together with its known structural invariants.

    Every field is a THEOREM about ξ(s), encoded as a type.
    We do not construct ξ — we axiomatize what ξ must satisfy
    and derive consequences from the axioms.

    The key axioms:
    - **Functional equation**: ξ(s) = ξ(1−s)
    - **Conjugation symmetry**: ξ(s̄) = ξ(s)̄
    - **Strip confinement**: zeros only in 0 < Re(s) < 1
    - **Existence of zeros**: the zero set is nonempty
    - **Real dimension**: dim_ℝ = 2^n checks for Clifford,
      here the analogous consistency is that ξ is determined
      by its values on the critical line -/
structure CompletedZetaData where
  /-- The completed zeta function ξ : ℂ → ℂ -/
  ξ : ℂ → ℂ
  /-- **Functional equation**: ξ(s) = ξ(1 − s).
      The global manifestation of Axiom I (Involution). -/
  hFuncEq : ∀ s : ℂ, ξ s = ξ (zetaReflection s)
  /-- **Conjugation symmetry**: ξ(s̄) = ξ(s)̄.
      Zeros come in conjugate pairs. -/
  hConjSym : ∀ s : ℂ, ξ (starRingEnd ℂ s) = starRingEnd ℂ (ξ s)
  /-- **Strip confinement**: all zeros lie in the critical strip.
      No zeros on Re(s) ≤ 0, Re(s) ≥ 1, or outside the strip. -/
  hZerosInStrip : ∀ s : ℂ, ξ s = 0 → s ∈ CriticalStrip
  /-- **Existence**: there exists at least one zero.
      (The zero set is infinite, but we only need nonemptiness.) -/
  hHasZero : ∃ ρ : ℂ, ξ ρ = 0

-- ═══════════════════════════════════════════════════════════════
-- Consequences of the axioms: zero pairing
-- ═══════════════════════════════════════════════════════════════

/-- **Zeros come in functional equation pairs.**

    If ξ(ρ) = 0, then ξ(1−ρ) = 0.

    Proof: ξ(ρ) = ξ(1−ρ) by the functional equation.
    So ξ(1−ρ) = ξ(ρ) = 0. -/
theorem zero_reflection (Z : CompletedZetaData) {ρ : ℂ}
    (h : Z.ξ ρ = 0) : Z.ξ (zetaReflection ρ) = 0 := by
  rw [← Z.hFuncEq]; exact h

/-- **Zeros come in conjugate pairs.**

    If ξ(ρ) = 0, then ξ(ρ̄) = 0.

    Proof: ξ(ρ̄) = ξ(ρ)̄ = 0̄ = 0. -/
theorem zero_conjugation (Z : CompletedZetaData) {ρ : ℂ}
    (h : Z.ξ ρ = 0) : Z.ξ (starRingEnd ℂ ρ) = 0 := by
  rw [Z.hConjSym, h, map_zero]

/-- The Schwarz reflection equals zetaReflection composed
    with conjugation (or vice versa — they commute). -/
theorem zetaSchwarzReflection_eq (s : ℂ) :
    zetaSchwarzReflection s = zetaReflection (starRingEnd ℂ s) := by
  rw [@Complex.ext_iff]
  simp only [zetaSchwarzReflection_re, zetaReflection_re, conj_re, zetaSchwarzReflection_im,
    zetaReflection_im, conj_im, neg_neg, and_self]

/-- **Zeros come in Schwarz pairs: the full V₄ orbit.**

    If ξ(ρ) = 0, then ξ(1 − ρ̄) = 0.

    Chain: ξ(ρ) = 0  →  ξ(ρ̄) = 0  →  ξ(1 − ρ̄) = 0. -/
theorem zero_schwarz (Z : CompletedZetaData) {ρ : ℂ}
    (h : Z.ξ ρ = 0) : Z.ξ (zetaSchwarzReflection ρ) = 0 := by
  rw [zetaSchwarzReflection_eq]
  exact zero_reflection Z (zero_conjugation Z h)

/-- The reflected zero is also in the critical strip. -/
theorem zero_reflection_in_strip (Z : CompletedZetaData) {ρ : ℂ}
    (h : Z.ξ ρ = 0) : zetaReflection ρ ∈ CriticalStrip :=
  Z.hZerosInStrip _ (zero_reflection Z h)

/-- From CompletedZetaData, extract a ZeroData for any zero. -/
def CompletedZetaData.mkZeroData (Z : CompletedZetaData)
    (ρ : ℂ) (hZero : Z.ξ ρ = 0) : ZeroData where
  ρ := ρ
  hStrip := Z.hZerosInStrip ρ hZero
  multiplicity := 1
  hMult := Nat.one_pos

end CompletedZeta


/-!
=====================================================================
## The Riemann Hypothesis as a Type
=====================================================================

The Riemann Hypothesis is the proposition that ALL non-trivial
zeros of ζ(s) lie on the critical line Re(s) = 1/2.

We state it as a predicate on `CompletedZetaData`, making it a
PROPERTY of the axiomatized ξ function.  This is the type that
the endgame file `Positivity.lean` aims to inhabit.

## Equivalent Formulations

RH has many equivalent statements.  We prove three equivalences
within the current vocabulary:

  (1) **Standard**: ∀ zeros ρ, Re(ρ) = 1/2
  (2) **Schwarz**: ∀ zeros ρ, zetaSchwarzReflection(ρ) = ρ
  (3) **Duality**: ∀ zeros ρ, zetaReflection(ρ) = conj(ρ)

All three say the same thing: the V₄ orbit of every zero
collapses to size ≤ 2.

=====================================================================
-/

section RiemannHypothesis

/-- **THE RIEMANN HYPOTHESIS.**

    All zeros of the completed zeta function lie on the
    critical line Re(s) = 1/2.

    This is a Prop — a type with at most one inhabitant.
    Proving RH means constructing a term of this type.
    Disproving it means constructing a term of its negation
    (exhibiting a zero off the line). -/
def CriticalLineConfinement (Z : CompletedZetaData) : Prop :=
  ∀ s : ℂ, Z.ξ s = 0 → s.re = 1 / 2

/-- RH equivalently: every zero is a Schwarz fixed point.

    The Schwarz reflection s ↦ 1 − s̄ fixes s iff Re(s) = 1/2. -/
theorem rh_iff_schwarz_fixes (Z : CompletedZetaData) :
    CriticalLineConfinement Z ↔
    (∀ s : ℂ, Z.ξ s = 0 → zetaSchwarzReflection s = s) := by
  constructor
  · intro h s hs
    rw [zetaSchwarzReflection_fixed_iff]
    exact h s hs
  · intro h s hs
    rw [← zetaSchwarzReflection_fixed_iff]
    exact h s hs

/-- RH equivalently: for every zero, its functional equation
    partner equals its conjugate.

    1 − ρ = ρ̄  ⟺  Re(ρ) = 1/2.

    This is the DUALITY formulation: the two generators σ and τ
    of V₄ agree on every zero.  The orbit collapses. -/
theorem rh_iff_reflection_eq_conj (Z : CompletedZetaData) :
    CriticalLineConfinement Z ↔
    (∀ s : ℂ, Z.ξ s = 0 →
      zetaReflection s = starRingEnd ℂ s) := by
  constructor
  · intro h s hs
    have hre := h s hs
    rw [@Complex.ext_iff]
    simp only [zetaReflection_re, conj_re, zetaReflection_im, conj_im, and_true]
    linarith
  · intro h s hs
    have heq := h s hs
    have hre : (zetaReflection s).re = (starRingEnd ℂ s).re := by rw [heq]
    simp at hre; linarith

/-- **RH implies all ZeroData are self-dual.** -/
theorem rh_implies_selfDual (Z : CompletedZetaData)
    (hRH : CriticalLineConfinement Z)
    (z : ZeroData) (hz : Z.ξ z.ρ = 0) : z.selfDual := by
  rw [z.selfDual_iff_onLine]
  exact hRH z.ρ hz

end RiemannHypothesis


/-!
=====================================================================
## Axiom I Interface: The Involution Data
=====================================================================

The `InvolutionData` structure packages the zeta reflection as
a reusable interface for the Möbius tooth profile.

`LocalFactor.lean` will instantiate `LocalToothProfile`, whose
first field is of type `InvolutionData`.  Every local factor —
archimedean and p-adic alike — must respect the SAME involution
s ↦ 1 − s.  This universality of the involution is what makes
the gear assembly possible: all gears turn on the same shaft.

Compare with the Tomita framework:
  - `InvolutionData.σ` is the analogue of J (modular conjugation)
  - `hInvol` is J² = 1
  - `hStrip` is "J maps M to M" (preserves the ambient structure)
  - `hFixed` is "JΩ = Ω" (identifies the fixed point / ground state)

The analogy is NOT exact — Axiom I is the weakest of the four
axioms.  But it is the one that ALL three Möbius twists (Bott,
CD, Tomita) share, and therefore the one that the number-theoretic
instantiation must satisfy first.

=====================================================================
-/

section InvolutionInterface

/-- **Axiom I data**: an involution on ℂ compatible with the
    critical strip geometry.

    This is the interface that every local factor must satisfy.
    It captures the MINIMAL content of the functional equation:
    a ℤ/2 symmetry of the ambient space with the critical line
    as its fixed locus. -/
structure InvolutionData where
  /-- The involution σ : ℂ → ℂ -/
  σ : ℂ → ℂ
  /-- σ is an involution: σ² = id -/
  hInvol : ∀ s : ℂ, σ (σ s) = s
  /-- σ preserves the critical strip -/
  hStrip : ∀ s : ℂ, s ∈ CriticalStrip → σ s ∈ CriticalStrip
  /-- The critical line is the real-part fixed locus of σ -/
  hFixed : ∀ s : ℂ, (σ s).re = s.re ↔ s.re = 1 / 2

/-- **The zeta reflection satisfies Axiom I.** -/
def zetaInvolutionData : InvolutionData where
  σ := zetaReflection
  hInvol := zetaReflection_involution
  hStrip := fun _ hs => zetaReflection_mem_strip hs
  hFixed := zetaReflection_re_fixed_iff

/-- The functional equation of CompletedZetaData is compatible
    with the Axiom I involution.

    ξ(s) = ξ(σ(s)) — the function is invariant under the
    involution.  This is what makes the involution PHYSICALLY
    meaningful: it's not just a symmetry of the strip, it's a
    symmetry of the function living on the strip. -/
theorem funcEq_compatible (Z : CompletedZetaData) :
    ∀ s : ℂ, Z.ξ s = Z.ξ (zetaInvolutionData.σ s) :=
  Z.hFuncEq

/-- **RH restated in tooth profile language.**

    The Riemann Hypothesis says: every zero of ξ is a fixed
    point of the Schwarz reflection, which is generated by
    combining Axiom I (zetaReflection) with Axiom II (to be
    defined — the anti-structure from complex conjugation).

    In gear language: the zero set lies on the AXLE of the
    Möbius gear — the line where the half-twist acts trivially. -/
theorem rh_as_axle_confinement (Z : CompletedZetaData) :
    CriticalLineConfinement Z ↔
    (∀ s : ℂ, Z.ξ s = 0 → s ∈ CriticalLine) := by
  simp [CriticalLineConfinement, CriticalLine]

end InvolutionInterface


end Riemann
